function [numerator, dist] = numer_posterior_probability_orientation(f_proj, f_image,...
    first_orientation, given_orientation, projection_parameters,...
    sigmaNoise, prior_parameters)
    
    max_angle_err = prior_parameters.max_angle_err;
    max_shift_err = prior_parameters.max_shift_err;
    
    [p_a, dist] = prob_of_proj_given_orientation_and_model(...
        f_proj, f_image, given_orientation, sigmaNoise, projection_parameters);
    p_b = prior_prob_orientation_given_model(...
        first_orientation, given_orientation, max_angle_err, max_shift_err);
    numerator = p_a*p_b;
end