function prob = posterior_prob_orientation(f_proj, f_image,...
    estimated_orientation, given_orientation, projection_parameters,...
    sigmaNoise, prior_parameters)
    
    n = numer_posterior_probability_orientation(f_proj, f_image,...
        estimated_orientation, given_orientation, projection_parameters,...
        sigmaNoise, prior_parameters);
    d = denom_posterior_probability_orientation(f_proj, f_image,...
        estimated_orientation, projection_parameters, sigmaNoise,...
        prior_parameters);

    prob = n/d;
end